### ISSUE TITLE
Feature request: Periodic restart

### ISSUE THREAD

**Issue by c-hri-s** [mikeburgh/subway#3]
I have an issue where watchtower updates running containers which subway is proxying, which obviously breaks the CF connection to that service.

Restarting subway is the answer, and then it re-estabilshes that connection, but it would be a nice feature to have the option for subway to restart the tunnel on a schedule (like nightly), to reconnect updated containers.

Appreciate this probably isn't a use-case for everyone, but thought I'd throw it out there.

**Comment by mikeburgh** [comment]
When watchtower does the update, does it restart the container ? I can probably make a change to listen for restarts in the CF mode and process those as well (should not be needed for Caddy since it's a stateless proxy).

**Comment by c-hri-s** [comment]
It trashes the container and pulls the newest version and deploys it. End result is the same named container with the same ports, etc. ... but I assume the process or stopping/rebuilding breaks the tunnel as any container which has updated becomes unavailable until I restart subway.

If there's a way to detect it and reset the tunnel, that would be amazing. My fallback was a hack of restarting subway overnight (after watchtower runs).

Thanks for considering this

**Comment by mikeburgh** [comment]
Can you trigger watchtower to do this manually and send the logs from the subway container during that process ?

It should be triggering stop and start events on the container so not sure why it would not be processing those on the tunnel correctly.. maybe it's too fast.. otherwise I can try and setup something to simulate it and see what happens.

**Comment by c-hri-s** [comment]
I have the logs from last night - watchtower runs at 2am, so this is what followed.
In the morning  audiobookshelf.mydomain.com was not available until I restarted subway

```
11/06/2023 2:03:19
2023-06-11T01:03:19Z SUBWAY Container prowlarr found with status start and subway.hostname prowlarr.mydomain.com...
11/06/2023 2:03:19
 - subway.port specified: 9696
11/06/2023 2:03:22
 - Checking connection to 172.19.0.3:9696.... nc: connect to 172.19.0.3 port 9696 (tcp) failed: Connection refused
11/06/2023 2:03:22
 - Failed to connect, ignoring
11/06/2023 2:03:27
2023-06-11T01:03:27Z SUBWAY Container audiobookshelf found with status start and subway.hostname audiobookshelf.mydomain.com...
11/06/2023 2:03:27
 - subway.port specified: 80
11/06/2023 2:03:30
 - Checking connection to 172.19.0.6:80.... nc: connect to 172.19.0.6 port 80 (tcp) failed: Connection refused
11/06/2023 2:03:30
 - Failed to connect, ignoring
12/06/2023 2:01:39
2023-06-12T01:01:39Z SUBWAY Container prowlarr found with status start and subway.hostname prowlarr.mydomain.com...
12/06/2023 2:01:40
 - subway.port specified: 9696
12/06/2023 2:01:42
 - Checking connection to 172.19.0.3:9696.... nc: connect to 172.19.0.3 port 9696 (tcp) failed: Connection refused
12/06/2023 2:01:42
 - Failed to connect, ignoring

```

**Comment by mikeburgh** [comment]
Perfect... okay so it's setting the start event from docker, but cannot connect to them. Since the restart of subway fixes that it maybe that some sort of timeout/retry is needed.. Let me add that in and you can see if that sorts it once I push it. 

Also, I assume watchtower is not changing the networks for the containers once they are started ? Eg when you restart subway, do the logs show the same IP's being used to connect to the containers and then connecting.

**Comment by c-hri-s** [comment]
The IP doesn't change, no:

```
12/06/2023 11:37:39
 - Adding audiobookshelf.mydomain.com to cloudflare tunnel via service http://172.19.0.6:80

```

The container takes a little while to spin up, so you're probably right that a retry once it's got its stuff together might be successful

**Comment by mikeburgh** [comment]
Sorry, just got back to this.

I just pushed a version that will wait 10 seconds when trying to connect to a container, and try every second to connect. 

You can see in the logs below, each . after the ip:port is a connection attempt, so it tried 10 times, then in this case joined the network the container is in and was able to instantly connect (single .) 

Let me know if this fixes the issue, otherwise I can bump it out past 10 seconds. 

```
- subway.port specified: 80
- Checking connection to 172.20.0.3:80........... nc: connect to 172.20.0.3 port 80 (tcp) timed out: Operation in progress
- Failed to connect, connecting to container networks and trying again
- Connecting to network cedcc
- Checking connection to 172.20.0.3:80. Connection to 172.20.0.3 80 port [tcp/http] succeeded!
 ```

**Comment by c-hri-s** [comment]
Thanks Mike - I'll pull it down and give it a go

**Comment by c-hri-s** [comment]
Seems to be working well, thanks!
